# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "385dd3ca01c61e11bc2fd374297ac8b1"
name = "shipping-bar"
handle = "shipping-bar-29"
application_url = "https://boy-expansion-description-resource.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-59632af1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://boy-expansion-description-resource.trycloudflare.com/auth/callback",
  "https://boy-expansion-description-resource.trycloudflare.com/auth/shopify/callback",
  "https://boy-expansion-description-resource.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
